name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  github-release:
    name: Publish GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CHGLOG_VERSION: "0.15.4"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate version changelog
      run: |
        set -euo pipefail
        export BASE_URL="https://github.com/git-chglog/git-chglog/releases/download"
        export FILENAME="git-chglog_${CHGLOG_VERSION}_linux_amd64.tar.gz"
        curl -fsSL "${BASE_URL}/v${CHGLOG_VERSION}/${FILENAME}" |sudo tar xz --no-same-owner -C /usr/local/bin git-chglog
        git-chglog --config .github/chglog/config.yml --output CHANGELOG.md "${GITHUB_REF_NAME}"

    - name: Create GitHub release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
      with:
        body_path: CHANGELOG.md

  docker-image:
    runs-on: ubuntu-latest
    needs: github-release
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0

      - name: Log in to Docker Hub registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: |
            docker.io/powerapi/hwpc-sensor
            ghcr.io/powerapi-ng/hwpc-sensor
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4.2.1
        id: build-and-push
        with:
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_TYPE=Release
